CREATE TABLE search_assist_responses (
    id SERIAL PRIMARY KEY,
    query TEXT,
    caret INT,
    ignore_unresolved_setting BOOLEAN DEFAULT FALSE,
    type VARCHAR(100) DEFAULT 'SearchAssistResponse'
);

CREATE TABLE search_style_ranges (
    id SERIAL PRIMARY KEY,
    response_id INT REFERENCES search_assist_responses(id) ON DELETE CASCADE,
    length INT,
    start_pos INT,
    style VARCHAR(100),
    title TEXT,
    type VARCHAR(100) DEFAULT 'SearchStyleRange'
);

CREATE TABLE search_suggestions (
    id SERIAL PRIMARY KEY,
    response_id INT REFERENCES search_assist_responses(id) ON DELETE CASCADE,
    description TEXT,
    suggestion_group VARCHAR(255),
    icon VARCHAR(255),
    suggestion_option TEXT,
    prefix TEXT,
    suffix TEXT,
    class_name VARCHAR(255),
    matching_start INT,
    matching_end INT,
    caret INT,
    completion_start INT,
    completion_end INT,
    type VARCHAR(100) DEFAULT 'SearchSuggestion'
);

CREATE TABLE search_sort_fields (
    id VARCHAR(100) PRIMARY KEY,
    name VARCHAR(255),
    sortable_presentation VARCHAR(255),
    type VARCHAR(100) DEFAULT 'SortField'
);

CREATE TABLE search_sort_properties (
    id SERIAL PRIMARY KEY,
    response_id INT REFERENCES search_assist_responses(id) ON DELETE CASCADE,
    property_id VARCHAR(100),
    asc_order BOOLEAN DEFAULT TRUE,
    sort_field_id VARCHAR(100) REFERENCES search_sort_fields(id),
    type VARCHAR(100) DEFAULT 'SortProperty'
);

CREATE TABLE search_query_features (
    id SERIAL PRIMARY KEY,
    response_id INT REFERENCES search_assist_responses(id) ON DELETE CASCADE,
    contains_wildcard BOOLEAN DEFAULT FALSE,
    contains_latin BOOLEAN DEFAULT TRUE,
    contains_digits BOOLEAN DEFAULT FALSE,
    contains_not_latin BOOLEAN DEFAULT FALSE,
    number_of_words INT DEFAULT 0,
    has_and BOOLEAN DEFAULT FALSE,
    has_or BOOLEAN DEFAULT FALSE,
    has_sorting BOOLEAN DEFAULT FALSE,
    query_length INT DEFAULT 0,
    fields_count INT DEFAULT 0,
    user_in_fields BOOLEAN DEFAULT FALSE,
    me_in_fields BOOLEAN DEFAULT FALSE,
    date_period_in_fields BOOLEAN DEFAULT FALSE,
    sorted_by_relevance BOOLEAN DEFAULT FALSE,
    sort_by_relevance_setting BOOLEAN DEFAULT FALSE,
    experiment_version VARCHAR(50),
    experiment_group VARCHAR(50),
    user_left_experiment BOOLEAN DEFAULT FALSE,
    is_guest BOOLEAN DEFAULT FALSE,
    is_internal BOOLEAN DEFAULT TRUE,
    is_jb_team BOOLEAN DEFAULT FALSE,
    folder_selected BOOLEAN DEFAULT FALSE,
    project_folder_selected BOOLEAN DEFAULT FALSE,
    saved_query_folder_selected BOOLEAN DEFAULT FALSE,
    tag_folder_selected BOOLEAN DEFAULT FALSE,
    is_single_issue BOOLEAN DEFAULT FALSE,
    is_tree_view BOOLEAN DEFAULT TRUE,
    query_computation_time_ms BIGINT DEFAULT 0,
    time_since_last_search_ms BIGINT DEFAULT 0,
    recent_searches_count INT DEFAULT 0,
    last_search_query_text_similarity DOUBLE PRECISION DEFAULT 0,
    last_search_query_token_similarity DOUBLE PRECISION DEFAULT 0,
    predefined_field_comment_text_field BOOLEAN DEFAULT FALSE,
    predefined_field_work_text_field BOOLEAN DEFAULT FALSE,
    predefined_field_vcs_changes_field BOOLEAN DEFAULT FALSE,
    predefined_field_ticket_cc_groups_field BOOLEAN DEFAULT FALSE,
    predefined_field_mentions_field BOOLEAN DEFAULT FALSE,
    predefined_field_underestimation_field BOOLEAN DEFAULT FALSE,
    predefined_field_saved_query_field BOOLEAN DEFAULT FALSE,
    predefined_field_content_field BOOLEAN DEFAULT FALSE,
    predefined_field_project_field BOOLEAN DEFAULT FALSE,
    predefined_field_star_field BOOLEAN DEFAULT FALSE,
    predefined_field_attachment_name_field BOOLEAN DEFAULT FALSE,
    predefined_field_voted_by_field BOOLEAN DEFAULT FALSE,
    predefined_field_article_field BOOLEAN DEFAULT FALSE,
    predefined_field_reaction_from_field BOOLEAN DEFAULT FALSE,
    predefined_field_by_field BOOLEAN DEFAULT FALSE,
    predefined_field_commented_by_field BOOLEAN DEFAULT FALSE,
    predefined_field_custom_field BOOLEAN DEFAULT FALSE,
    predefined_field_code_field BOOLEAN DEFAULT FALSE,
    predefined_field_ticket_cc_field BOOLEAN DEFAULT FALSE,
    predefined_field_summary_field BOOLEAN DEFAULT FALSE,
    predefined_field_mentioned_in_field BOOLEAN DEFAULT FALSE,
    predefined_field_organization_field BOOLEAN DEFAULT FALSE,
    predefined_field_issue_field BOOLEAN DEFAULT FALSE,
    predefined_field_votes_field BOOLEAN DEFAULT FALSE,
    predefined_field_attachments_field BOOLEAN DEFAULT FALSE,
    predefined_field_links_field BOOLEAN DEFAULT FALSE,
    predefined_field_title_field BOOLEAN DEFAULT FALSE,
    predefined_field_work_field BOOLEAN DEFAULT FALSE,
    predefined_field_attachment_text_field BOOLEAN DEFAULT FALSE,
    predefined_field_comments_field BOOLEAN DEFAULT FALSE,
    predefined_field_document_type_field BOOLEAN DEFAULT FALSE,
    predefined_field_action_field BOOLEAN DEFAULT FALSE,
    predefined_field_has_field BOOLEAN DEFAULT FALSE,
    predefined_field_similar_to_field BOOLEAN DEFAULT FALSE,
    predefined_field_tag_field BOOLEAN DEFAULT FALSE,
    predefined_field_description_field BOOLEAN DEFAULT FALSE,
    predefined_field_visible_to_field BOOLEAN DEFAULT FALSE,
    predefined_field_sort_by_field BOOLEAN DEFAULT FALSE,
    predefined_field_commented_field BOOLEAN DEFAULT FALSE,
    predefined_field_article_author_field BOOLEAN DEFAULT FALSE,
    predefined_field_updated_by_field BOOLEAN DEFAULT FALSE,
    predefined_field_submitted_by_field BOOLEAN DEFAULT FALSE,
    predefined_field_resolved_field BOOLEAN DEFAULT FALSE,
    predefined_field_created_field BOOLEAN DEFAULT FALSE,
    predefined_field_updated_field BOOLEAN DEFAULT FALSE,
    type VARCHAR(100) DEFAULT 'SearchQueryFeatures'
);
