services:
  postgres:
    image: postgres:16-alpine
    container_name: youtrack_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: youtrack_db
    ports:
      - "8090:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations/000001_init_schema.up.sql:/docker-entrypoint-initdb.d/01_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d youtrack_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
