INSERT INTO user_groups (id, name, group_type, all_users_group, description) VALUES
('all-users', 'All Users', 'AllUsersGroup', TRUE, 'All user accounts are automatically added to the All Users group. By default, this group is not assigned any role in any project.'),
('registered-users', 'Registered Users', 'RegisteredUsersGroup', FALSE, 'When a user account is created, it is automatically added to the Registered Users group. By default, this group is assigned the Observer role in the Global project.');


INSERT INTO roles (id, name, description, is_updatable, immutable, permissions) VALUES
('system-admin', 'System Admin', 'Superuser with access to every permission', FALSE, TRUE,
 ARRAY[
   'read-project-basic',
   'create-project',
   'read-project-full',
   'update-project',
   'delete-project',
   'read-organization',
   'update-organization',
   'create-organization',
   'delete-organization',
   'update-self',
   'read-user-basic',
   'read-user-details',
   'update-user',
   'create-user',
   'delete-user',
   'low-level-admin-read',
   'low-level-admin-write',
   'read-issue',
   'read-issue-private-fields',
   'update-issue',
   'create-issue',
   'delete-issue',
   'link-issues',
   'update-issue-private-fields',
   'apply-commands-silently',
   'view-watchers',
   'update-watchers',
   'view-voters',
   'add-attachment',
   'update-attachment',
   'delete-attachment',
   'create-issue-comment',
   'read-issue-comment',
   'update-issue-comment',
   'delete-issue-comment',
   'update-not-own-issue-comment',
   'delete-not-own-comment-and-permanent-comment-delete',
   'read-article-comment',
   'create-article-comment',
   'update-article-comment',
   'delete-article-comment',
   'override-visibility-restrictions',
   'read-work-item',
   'update-work-item',
   'update-not-own-work-item',
   'create-work-item',
   'create-not-own-work-item',
   'read-article',
   'create-article',
   'update-article',
   'delete-article',
   'read-app-content',
   'update-app-content'
 ]),
('project-admin', 'Project Admin', 'Full control over projects, issues and members', FALSE, FALSE,
 ARRAY[
   'read-project-basic',
   'create-project',
   'read-project-full',
   'update-project',
   'delete-project',
   'read-organization',
   'update-organization',
   'create-organization',
   'delete-organization',
   'read-user-basic',
   'read-user-details',
   'create-user',
   'update-user',
   'delete-user',
   'update-self',
   'read-issue',
   'read-issue-private-fields',
   'update-issue',
   'create-issue',
   'delete-issue',
   'link-issues',
   'update-issue-private-fields',
   'apply-commands-silently',
   'view-watchers',
   'update-watchers',
   'view-voters',
   'add-attachment',
   'update-attachment',
   'delete-attachment',
   'create-issue-comment',
   'read-issue-comment',
   'update-issue-comment',
   'delete-issue-comment',
   'update-not-own-issue-comment',
   'delete-not-own-comment-and-permanent-comment-delete',
   'read-article-comment',
   'create-article-comment',
   'update-article-comment',
   'delete-article-comment',
   'override-visibility-restrictions',
   'read-work-item',
   'update-work-item',
   'update-not-own-work-item',
   'create-work-item',
   'create-not-own-work-item',
   'read-article',
   'create-article',
   'update-article',
   'delete-article',
   'read-app-content'
 ]),
('contributor', 'Contributor', 'Standard member with basic create/read/edit capabilities', TRUE, FALSE,
 ARRAY[
   'read-project-basic',

   'read-issue',
   'read-issue-private-fields',
   'update-issue',
   'create-issue',
   'delete-issue',
   'link-issues',
   'update-issue-private-fields',
   'view-watchers',
   'update-watchers',
   'view-voters',

   'add-attachment',
   'update-attachment',
   'delete-attachment',

   'create-issue-comment',
   'read-issue-comment',
   'update-issue-comment',
   'delete-issue-comment',
   'read-article-comment',
   'create-article-comment',

   'read-work-item',
   'update-work-item',
   'create-work-item',
   
   'read-article',
   'create-article'

 ]),
('observer', 'Observer', 'The Observer role grants baseline access to interact with other registered users in the system', TRUE, FALSE,
 ARRAY[
   'update-self',
   'read-user-basic',
   'read-user-details'
 ]),
('user-manager', 'User Manager', 'The Observer role grants baseline access to interact with other registered users in the system', TRUE, FALSE,
 ARRAY[
   'create-user'
 ]),
('project-creator', 'Project Creator', 'The Observer role grants baseline access to interact with other registered users in the system', TRUE, FALSE,
 ARRAY[
   'create-user'
 ]);


ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_login_count INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_failed_login_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

